FROM ubuntu:16.10
MAINTAINER M. Peter <mp@tcs.de>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -qq update
RUN apt-get install -y nodejs npm
# TODO could uninstall some build dependencies

# fucking debian installs `node` as `nodejs`
RUN update-alternatives --install /usr/bin/node node /usr/bin/nodejs 10

RUN	mkdir -p /usr/src/
WORKDIR /usr/src/

COPY issue78/issue78.js /usr/src/issue78.js
RUN node -v
RUN npm -v

RUN npm install node-cache


CMD [ "node", "issue78.js" ]
