FROM ubuntu:14.04
MAINTAINER M. Peter <mp@tcs.de>

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -qq update
RUN apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
RUN apt-get install -y nodejs

RUN	mkdir -p /usr/src/
WORKDIR /usr/src/

COPY issue78/issue78.js /usr/src/issue78.js
RUN node -v
RUN npm -v

RUN npm install node-cache


CMD [ "node", "issue78.js" ]
